import {
    // HiOutlineChartSquareBar,
    HiOutlineUserGroup,
    HiOutlineRocketLaunch,
    HiOutlineUserCircle,
    HiOutlineBookOpen,
    HiOutlineCurrencyDollar,
    HiOutlineShieldCheck,
    // HiOutlineColorSwatch,
    // HiOutlineChatAlt,
    // HiOutlineDesktopComputer,
    HiOutlinePaperAirplane,
    HiOutlineChartPie,
    // HiOutlineUserAdd,
    HiOutlineKey,
    // HiOutlineBan,
    // HiOutlineHand,
    HiOutlineDocumentText,
    // HiOutlineTemplate,
    HiOutlineLockClosed,
    HiOutlineDocumentDuplicate,
    HiOutlineSquares2X2,
    // HiOutlineHome,
    // HiOutlineUserCircle,
    HiOutlineShare,
    HiOutlineVariable,
    // HiOutlineCode,
    HiOutlineWallet,
    HiOutlineArrowsRightLeft,
} from 'react-icons/hi2'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    apps: <HiOutlineSquares2X2 />,
    // project: <HiOutlineChartSquareBar />,
    crm: <HiOutlineUserGroup />,
    sales: <HiOutlineRocketLaunch />,
    crypto: <HiOutlineCurrencyDollar />,
    knowledgeBase: <HiOutlineBookOpen />,
    account: <HiOutlineUserCircle />,
    // uiComponents: <HiOutlineTemplate />,
    // common: <HiOutlineColorSwatch />,
    // feedback: <HiOutlineChatAlt />,
    // dataDisplay: <HiOutlineDesktopComputer />,
    forms: <HiOutlineDocumentText />,
    navigation: <HiOutlinePaperAirplane />,
    graph: <HiOutlineChartPie />,
    authentication: <HiOutlineLockClosed />,
    signIn: <HiOutlineShieldCheck />,
    // signUp: <HiOutlineUserAdd />,
    forgotPassword: <HiOutlineLockClosed />,
    resetPassword: <HiOutlineKey />,
    pages: <HiOutlineDocumentDuplicate />,
    // welcome: <HiOutlineHand />,
    // accessDenied: <HiOutlineBan />,
    guide: <HiOutlineBookOpen />,
    documentation: <HiOutlineDocumentText />,
    sharedComponentDoc: <HiOutlineShare />,
    utilsDoc: <HiOutlineVariable />,
    // changeLog: <HiOutlineCode />,
    wallet: <HiOutlineWallet />,
    channel: <HiOutlineArrowsRightLeft />,
}

export default navigationIcon
